---
- name: install tomcat10 and tomcat10-admin with using loops
  hosts: all
  tasks: 
    - name: install tomcat10 and tomcat10-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
       - {a: tomcat10, b: present, c: yes}
       - {a: tomcat10-admin, b: present, c: no}
...         
